//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResponder.Web.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AC_Entities : DbContext
    {
		public AC_Entities()
			: base("name=AC_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BR_AccessControl_Action> BR_AccessControl_Action { get; set; }
        public DbSet<BR_AccessControl_Application> BR_AccessControl_Application { get; set; }
        public DbSet<BR_AccessControl_Role> BR_AccessControl_Role { get; set; }
        public DbSet<BR_AccessControl_User> BR_AccessControl_User { get; set; }
    }
}
