//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResponder.Web.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BR_AccessControl_User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Trigram { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
    
        public virtual BR_AccessControl_Role BR_AccessControl_Role { get; set; }
    }
}
