//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResponder.Web.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BR_AutoResponder_Template
    {
        public BR_AutoResponder_Template()
        {
            this.BR_AutoResponder_Sending = new HashSet<BR_AutoResponder_Sending>();
        }
    
        public int Id { get; set; }
        public int SendingListId { get; set; }
        public int Sequence { get; set; }
        public Nullable<int> Interval { get; set; }
        public string Sender { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
    
        public virtual ICollection<BR_AutoResponder_Sending> BR_AutoResponder_Sending { get; set; }
        public virtual BR_AutoResponder_SendingList BR_AutoResponder_SendingList { get; set; }
    }
}
