//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResponder.Web.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BR_AutoResponder_UserEntry
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int SendingListId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public bool Optin { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
    
        public virtual BR_Users BR_Users { get; set; }
        public virtual BR_AutoResponder_SendingList BR_AutoResponder_SendingList { get; set; }
    }
}
