//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResponder.Web.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BR_AutoResponder_Sending
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int TemplateId { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<bool> Unsubscribe { get; set; }
        public Nullable<bool> OpenMail { get; set; }
        public Nullable<bool> Bounce { get; set; }
        public Nullable<bool> Click { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
    
        public virtual BR_Users BR_Users { get; set; }
        public virtual BR_AutoResponder_Template BR_AutoResponder_Template { get; set; }
    }
}
