//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResponder.Web.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BR_AutoResponder_SendingList
    {
        public BR_AutoResponder_SendingList()
        {
            this.BR_AutoResponder_UserEntry = new HashSet<BR_AutoResponder_UserEntry>();
            this.BR_AutoResponder_Template = new HashSet<BR_AutoResponder_Template>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Interval { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string Tags { get; set; }
    
        public virtual ICollection<BR_AutoResponder_UserEntry> BR_AutoResponder_UserEntry { get; set; }
        public virtual ICollection<BR_AutoResponder_Template> BR_AutoResponder_Template { get; set; }
    }
}
