//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResponder.Web.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BR_Users> BR_Users { get; set; }
        public DbSet<BR_AutoResponder_Tag> BR_AutoResponder_Tag { get; set; }
        public DbSet<BR_AutoResponder_Sending> BR_AutoResponder_Sending { get; set; }
        public DbSet<BR_AutoResponder_UserEntry> BR_AutoResponder_UserEntry { get; set; }
        public DbSet<BR_AutoResponder_SendingList> BR_AutoResponder_SendingList { get; set; }
        public DbSet<BR_AutoResponder_Template> BR_AutoResponder_Template { get; set; }
    }
}
